### ISSUE TITLE
Start its own daemon

### ISSUE THREAD

**Issue by gaborbernat** [lensvol/intellij-blackconnect#11]
Could there be an option to automatically start a blackd process in the background if there's no such thing yet?

**Comment by Keou0007** [comment]
I would like to upvote this. Currently when blackconnect complains that about a missing connection I open a new Terminal tab in pycharm and run it from there and just leave it running until I quit Pycharm. I assume that would be easy enough to script in a plugin, although I have 0% experience with plugins or Java. Based on other plugins I used, seems like it should be possible to give blackconnect its own tab that can show the log output and have a couple buttons for triggering actions.

**Comment by lensvol** [comment]
Thank you for showing interest!

This feature is planned to appear in the next release. Development was halted for personal reasons, but now I am slowly returning to it. :) Hopefully, it will see the light of day by the end of October.

**Comment by Keou0007** [comment]
that's great news, thanks for your work :)

**Comment by dmwyatt** [comment]
@lensvol Any progress on this?

**Comment by lensvol** [comment]
@dmwyatt Bulk of the code is already there, actually. However, I was forced to stop the development due to personal reasons and just now slowly get back on track with it. 

It is possible that it will make it into 0.5.0 release later this month, but I can only ask for your patience.

**Comment by dmwyatt** [comment]
> but I can only ask for your patience.

No way. I demand it now!  

Just kidding, it's no big deal.  Thanks for your work!

**Comment by studioj** [comment]
could it be possible to add this as a configuration option? => since I'm using a remote blackd server i dont want to run it locally

**Comment by lensvol** [comment]
@studioj Yes, that is the intended mode of operation. Starting your own daemon exists as an option alongside usual way of doing things.

**Comment by lensvol** [comment]
> Hi @lensvol. Is there any updates? Maybe i can help you with somthing?

No, thank you, all is fine. :) There it's only a minor feature left to implement (auto-detection of an existing **blackd** installation), but work has somewhat due to personal reasons and lack of inspiration.

Hopefully it will all change soon enough :)

**Comment by sergeyshevch** [comment]
Ok it will be perfect. For now i just added startup task for start blackd

**Comment by andrewjong** [comment]
Hi, are there any updates on this?

**Comment by lensvol** [comment]
@andrewjong It is actually mostly done and I've been using privately for about half a year now. Thing is that it lacks polish right now :/

I have vague plans for releasing it round Christmas, so stay tuned!

**Comment by ilkersigirci** [comment]
Great to hear that, I am also waiting this feature. I hope it will come in the next future release

**Comment by flisboac** [comment]
Would it be too difficult for the plugin to instantiate a daemon for each "project dependency" ([as in a multi-project setup](https://www.jetbrains.com/help/pycharm/2021.3/open-projects.html#multiple); weird terminology) opened together with a specific project?

**Comment by lyh543** [comment]
Since version [0.5.0](https://plugins.jetbrains.com/plugin/14321-blackconnect/versions/stable/169974) has already been released, the issue can be closed right now👍 @gaborbernat @lensvol

**Comment by Keou0007** [comment]
Amazing! Thanks @lensvol :)

**Comment by lensvol** [comment]
Don't forget to leave a review :D
