### ISSUE TITLE
Inconsistent format indent on method definition or if condition

### ISSUE THREAD

**Issue by tutunana** [lensvol/intellij-blackconnect#12]
Hi,

Currently, when I use `blackd` and `blackconnect`, sometimes the method definition `def abc(...)` with a number of params, I noticed that the indent can change randomly.
When I call `black` from terminal, the indent can be formatted correctly.
Same issue also randomly happens on `if` condition.

Not quite sure it is the issue from `blackd` or `blackconnect` but I guess not from `black` itself.
Do you see the same issue?

I have tested on latest `black` and `blackconnect`, on OSX and Ubuntu 20.04.

**Comment by lensvol** [comment]
Thank you for reporting this!

Does it happen when you try to reformat a fragment or when you reformat the whole file (explicitly or on save)? 
If you can also provide a snippet that has triggered that, it would also help a lot. :)

**Comment by tutunana** [comment]
@lensvol I have captured the issue on some random code. Please take a look.
https://drive.google.com/file/d/151-mnmwXPpyrcUchOAz6pkzf3XY6ObSv/view?usp=sharing

**Comment by lensvol** [comment]
I've checked with the latest version of the plugin and **black** version _20.8b1_. Over several invocations of **blackd** of the same version + plugin, it seems to produce identical code both with the direct call of **black**.

Reformatted code:
```python
class A:
    def test_black_format(
        self,
        param_a: int,
        param_b: int,
        param_c: dict,
        param_d: dict,
    ):
        print(param_a)
        print(param_b)
        print(param_c)
        print(param_d)
        if (
            param_a
            and param_b
            and param_c
            and param_d
            and param_a > param_b
            and param_c.get("test") is not None
        ):
            return False
        return True
```

Can you please describe in more detail how you trigger this behavior? 

Also, please check that there is no **black** hook enabled in _Settings / File Watchers_ or somewhere else in your environment.

**Comment by tutunana** [comment]
@lensvol I tested by adding some changes like in the clip and then Ctrl-S.
I think it's fine now when I disable `Reformat file on save` of `Save Actions` plugins.
So I guess it's an issue with compatibility between `black connect` and `save actions` plugin, and the save events are received and processed at random sequence.

**Comment by lensvol** [comment]
Thank you for this information! :)

Maybe it will be prudent to check for the presence of that plugin and ask the user to disable "Reformat on save" if it is enabled. I will see if it is possible to do it in one of the future releases.

**Comment by tutunana** [comment]
@lensvol my current workaround is to enable the reformat file on save but only with the scope of file types (for me the *.js, *.vue, *.html).
I suggest a simple line on README.md about this behavior so that someone can get attention when running into the same problem.

**Comment by lensvol** [comment]
Added warning in beb375a.
