### ISSUE TITLE
Any plans for supporting formatting all files in subdirectories of selected folder?

### ISSUE THREAD

**Issue by Krande** [lensvol/intellij-blackconnect#13]
Hi,

first of all thanks for this awesome plugin! I was just wondering if there are any plans (if at all possible or if not this functionality is by design omitted ?) to incorporate support for formatting all files in subdirectories of a selected folder in the project outliner?

Let me know if the question is unclear or if there is anything else I can help with solving this issue:)

Best regards
Kristoffer

**Comment by lensvol** [comment]
Thank you for the kind words!

Your desired functionality diverges from the main purpose of this plugin: minimizing latency for reformatting the code you are working with _right now_, and thus probably will not be implemented in the near future. Also, it can be achieved by just running `black` once manually. :) 

On the other hand, it can certainly come in handy if we go down the road of tighter integration with the `black` itself. I have nothing against your wish on principle and will welcome any PRs implementing it. :)

Kind regards,
Kirill

**Comment by Krande** [comment]
Okay, that is a fair answer :) I might dabble a bit with the plugin code and see if I get something working locally. If I get something working that seems stable enough (and that I find myself using enough) I can create a pull request :) Until then I'll close this issue given that you gave me answer I was looking for!

Thank you and Best Regards
Kristoffer
