### ISSUE TITLE
How to configure extra flags? 

### ISSUE THREAD

**Issue by igor-arteria** [lensvol/intellij-blackconnect#16]
I was looking to use black with some extra flags. 

Like for example: `--skip-string-normalization`.  Which translates in to sensing this header in request: `X-Skip-String-Normalization`

Is it possible to configure this for demon somehow? It seems like demon is accepting these parameters in headers.

**Comment by lensvol** [comment]
Hi.

Actually, almost all of the flags currently supported by `blackd` are already exposed and configurable via _BlackConnect_ pane in IDE "Preferences".

If there is any option that is missing, please feel free to create a specific issue or, if you prefer, submit a PR. :)

**Comment by igor-arteria** [comment]
Ahh, feel so stupid :)

Here it is:

<img width="1109" alt="Screen Shot 2021-01-22 at 9 15 53 AM" src="https://user-images.githubusercontent.com/74982558/105501714-8d44a980-5c92-11eb-9efa-04c566d06971.png">
