### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by kst83** [lensvol/intellij-blackconnect#17]
I'd like to use this plugin as it looks very useful, but in order to get it approved I need information on how it handles privacy.
Does it collect any personal information?
If so, what kind of data is collected and when is it collected?
Would also be great if you could add this to the documentation.

Thank you very much!

**Comment by lensvol** [comment]
The only case when plugin contacts external servers and sends any information collected from your computer is when you _voluntarily_ choose to report any internal exceptions to our [https://sentry.io](sentry.io) installation.

In addition to any data outlined in [https://sentry.io/privacy/](Sentry privacy policy), we also collect following data points:
* Stack trace of the exception inside the plugin
* Plugin's release number

Again, this only occurs in very rare cases and requires an explicit action by the user. When asked, he is also reminded that data collection falls under Sentry guidelines mentioned earlier.

I will update README.md to better reflect this in the future. :)

Hope that helps!
