### ISSUE TITLE
preview option support

### ISSUE THREAD

**Issue by Mogost** [lensvol/intellij-blackconnect#37]
[intellij-blackconnect](https://github.com/lensvol/intellij-blackconnect) does not respect blacks `preview` option
```
preview = true
```
https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#preview-style

**Comment by lensvol** [comment]
Sorry for the late reply, I was on vacation.

Sadly, the problem here is that there is no way to pass this option to the **blackd** itself, see [protocol documentation](https://black.readthedocs.io/en/stable/usage_and_configuration/black_as_a_server.html#protocol). :(

I am thinking about making it possible via a commit there, but it may take some time. Until then the issue will be closed as not being the fault of the plugin itself.

**Comment by Mogost** [comment]
Ouch. I didn't know blackd didn't have support for this. It seems to be just an oversight on their part. 
Should I create an issue in black github? Looks very easy to resolve

**Comment by lensvol** [comment]
Please do. As soon as it is merged I'll get right down to implementing it.

**Comment by Mogost** [comment]
Will be added in the next release of black. I think this can be reopened

**Comment by KotlinIsland** [comment]
[Black 22.8.0 was released](https://github.com/psf/black/releases/tag/22.8.0#:~:text=own%20line%20(%233227)-,blackd,-blackd%20now%20supports) with this feature, feature can be implemented now 🚀🚀🚀

**Comment by Mogost** [comment]
Hopefully this will be fixed soon. In fact, this is a blocking problem for me.
Since I am using the preview style in my project. 
And intellij-blackconnect formats the code and in some files it formats differently than just running black. Then I don't notice changes, push to a repo and CI tests fall :)

**Comment by KotlinIsland** [comment]
- I re-raised this issue in #51

**Comment by lensvol** [comment]
Yes, hopefully I can get around to implementing that feature this week.

**Comment by KotlinIsland** [comment]
I've just implemented it

**Comment by KotlinIsland** [comment]
Requesting feedback for the PR: #52

**Comment by lensvol** [comment]
Solved by #52

**Comment by Mogost** [comment]
Could we have a new release with this fix?

**Comment by lensvol** [comment]
There is a possibility that a new patch-level release will be ready in a couple of days. Please be patient.

**Comment by Mogost** [comment]
@lensvol Sorry for pinging again. Could we have a release?

**Comment by lensvol** [comment]
*sigh* I really should do that, yes.

Will try to implement support for 3.11 and release before this week ends.

**Comment by lensvol** [comment]
@Mogost It has been released.

**Comment by Mogost** [comment]
@lensvol thank you for your present for my birthday 😃
