### ISSUE TITLE
Default line-length parameter in blackconnect differs from default value in black

### ISSUE THREAD

**Issue by Pitirus** [lensvol/intellij-blackconnect#5]
In black default `--line-length=88` in blackconnect it's `80`.

Small change but brings confusion and changes formatting of files.

**Comment by lensvol** [comment]
Thank you! Good catch! 

It was actually set to 88 in the "Settings" panel, but I forgot to update defaults in the config itself. Will fix it soon. :)

**Comment by lensvol** [comment]
Fixed in https://github.com/lensvol/intellij-blackconnect/commit/690bbc0812b98e3564e6b78361b0a8630fec69c4, included into `0.3.1` release. Hopefully, it gets approved soon. :)
