### ISSUE TITLE
(🎁) Respect `exclude`, `extend-exclude` and `include` from `pyproject.toml`

### ISSUE THREAD

**Issue by KotlinIsland** [lensvol/intellij-blackconnect#56]
BlackConnect is formatting files that are marked as exclude in the config file, this is very frustrating.

**Comment by lensvol** [comment]
This is not a new request, see #27. I plan to include it into either next release or the one after.

**Comment by KotlinIsland** [comment]
Duplicate of #27

**Comment by KotlinIsland** [comment]
Duplicate of #27
