### ISSUE TITLE
(🎁) Add a shortcut to set the IDE vertical rule / line length / 'Hard wrap at'

### ISSUE THREAD

**Issue by KotlinIsland** [lensvol/intellij-blackconnect#57]
Not many people actually know about this setting, I think it's a good one.

A "Set in IDE" button could be added here:
![image](https://user-images.githubusercontent.com/65446343/189466207-f13cf21e-5f05-48a9-9c23-6bb25bea941b.png)

And it would update the IDE's project level settings to match the selection.

If fact, this should be heavily emphasized.

**Comment by lensvol** [comment]
I think this is out of scope for this plugin.

**Comment by KotlinIsland** [comment]
Okay, but in my opinion, this plugin is "add black support to Idea", and if black is specifying a line length, then it makes sense that the plugin would change Idea to reflect that.

If I implemented this would you accept the change?
