### ISSUE TITLE
Issue with blackconnect in DataSpell

### ISSUE THREAD

**Issue by soumen-ghosh** [lensvol/intellij-blackconnect#60]
Hi,

I’m trying to enable the “black” code formatter in DataSpell. I’ve followed the instructions from the below link –

https://black.readthedocs.io/en/stable/integrations/editors.html

After doing all the settings, this is how my settings look:

![DataSpell-BlackConnect](https://user-images.githubusercontent.com/84480006/189772758-2f28e8d7-01bc-4965-b47e-5b201d6b8e4e.jpg)

However, while saving a changed file, I’m getting this error –
![DataSpell-BlackConnect-Issue](https://user-images.githubusercontent.com/84480006/189772855-52f0f9a9-64b5-40e8-8863-e18c3b109f7a.jpg)

What should I check to resolve the issue?

**Comment by soumen-ghosh** [comment]
This is on CentOS7.

**Comment by lensvol** [comment]
You start **blackd** and ask it to listen for incoming connections on port 45485.

Then you specify that plugin should connect to **blackd** on port 45484.

As you can see, it would fail to do so. Please correct either of those numbers to bring it in sync with the other one.

Hope that helps.

**Comment by soumen-ghosh** [comment]
Thanks - it's an oversight. I changed the default port while starting as that was already being used. After making both port to same number, it worked.
