### ISSUE TITLE
manual format code work well, but before commit reformat not work

### ISSUE THREAD

**Issue by gshmu** [lensvol/intellij-blackconnect#69]
![image](https://user-images.githubusercontent.com/1797676/212223728-8b5c0aac-2ac2-4f8a-87fd-046e8a012bb6.png)

thanks.

**Comment by lensvol** [comment]
Interesting. This may be out of scope for the extension if IDEA uses different reformat mechanisms between dropdown menu and this one.

Thank you!

**Comment by gshmu** [comment]
https://youtrack.jetbrains.com/issue/PY-58725/IDEA-uses-different-reformat-mechanisms
