### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by xSAVIKx** [lensvol/intellij-blackconnect#70]
Hey, thx for the awesome plugin!

It'd be great to introduce support for Python3.11. `black` already has support for 3.11, so it probably makes sense :-)

If there are some docs regarding to how better implement the support, I may jump in and prepare a PR.

**Comment by lensvol** [comment]
Thank you for your kind words!

Yes, I've been dragging my feet in regards with pushing a new release out the door 🙃

The plan is to finally do a new release this week and this seems like a good feature to fit into it.

If you still would like to do it yourself, then phrase refer to a PR that implements support for 3.10: https://github.com/lensvol/intellij-blackconnect/pull/33

Godspeed!
