### ISSUE TITLE
Stop notifying "blackd already started"

### ISSUE THREAD

**Issue by lofidevops** [lensvol/intellij-blackconnect#82]
**Problem statement:**

Every time I launch the IDE or open a new project (multiple times per day) I get a info notification saying "BlackConnect: blackd already started (PID:12345)"

This contributes to notification fatigue.

**Suggested solution:**

* Do not display this notification. It merely confirms "Everything is working" status.
* Instead display error notifications for errors, timeouts, and other failures to achieve "Everything is working" status.
* Perhaps display a notification if BlackConnect initiates a launch of the blackd process? That workflow doesn't apply to me, so I can't comment on frequency and notification fatigue.

**Comment by lensvol** [comment]
Thank you for reporting this!

I agree, currently this notification serves no useful purpose if the current IDE instance already has launched **blackd**. It will be removed in future versions.

**Comment by lensvol** [comment]
Implemented in release 0.6.1
